/**
 * かな → ローマ字表記の対応表。
 * 各配列は優先順位順で、先頭がローマ字ガイドのデフォルト表示に使われる。
 * 「ん」「っ」は文脈依存のため対応表に持たず、セッション側で特別扱いする。
 */

/** 1かなで完結する表記 */
export const SINGLE: Readonly<Record<string, readonly string[]>> = {
  あ: ['a'],
  い: ['i', 'yi'],
  う: ['u', 'wu', 'whu'],
  え: ['e'],
  お: ['o'],
  か: ['ka', 'ca'],
  き: ['ki'],
  く: ['ku', 'cu', 'qu'],
  け: ['ke'],
  こ: ['ko', 'co'],
  さ: ['sa'],
  し: ['si', 'shi', 'ci'],
  す: ['su'],
  せ: ['se', 'ce'],
  そ: ['so'],
  た: ['ta'],
  ち: ['ti', 'chi'],
  つ: ['tu', 'tsu'],
  て: ['te'],
  と: ['to'],
  な: ['na'],
  に: ['ni'],
  ぬ: ['nu'],
  ね: ['ne'],
  の: ['no'],
  は: ['ha'],
  ひ: ['hi'],
  ふ: ['hu', 'fu'],
  へ: ['he'],
  ほ: ['ho'],
  ま: ['ma'],
  み: ['mi'],
  む: ['mu'],
  め: ['me'],
  も: ['mo'],
  や: ['ya'],
  ゆ: ['yu'],
  よ: ['yo'],
  ら: ['ra'],
  り: ['ri'],
  る: ['ru'],
  れ: ['re'],
  ろ: ['ro'],
  わ: ['wa'],
  を: ['wo'],
  が: ['ga'],
  ぎ: ['gi'],
  ぐ: ['gu'],
  げ: ['ge'],
  ご: ['go'],
  ざ: ['za'],
  じ: ['zi', 'ji'],
  ず: ['zu'],
  ぜ: ['ze'],
  ぞ: ['zo'],
  だ: ['da'],
  ぢ: ['di'],
  づ: ['du'],
  で: ['de'],
  ど: ['do'],
  ば: ['ba'],
  び: ['bi'],
  ぶ: ['bu'],
  べ: ['be'],
  ぼ: ['bo'],
  ぱ: ['pa'],
  ぴ: ['pi'],
  ぷ: ['pu'],
  ぺ: ['pe'],
  ぽ: ['po'],
  ゔ: ['vu'],
  ぁ: ['xa', 'la'],
  ぃ: ['xi', 'li'],
  ぅ: ['xu', 'lu'],
  ぇ: ['xe', 'le'],
  ぉ: ['xo', 'lo'],
  ゃ: ['xya', 'lya'],
  ゅ: ['xyu', 'lyu'],
  ょ: ['xyo', 'lyo'],
  ゎ: ['xwa', 'lwa'],
  ー: ['-'],
};

/** 2かな(拗音・外来音)で完結する表記 */
export const DIGRAPH: Readonly<Record<string, readonly string[]>> = {
  きゃ: ['kya'],
  きゅ: ['kyu'],
  きょ: ['kyo'],
  しゃ: ['sya', 'sha'],
  しゅ: ['syu', 'shu'],
  しょ: ['syo', 'sho'],
  しぇ: ['sye', 'she'],
  ちゃ: ['tya', 'cha', 'cya'],
  ちゅ: ['tyu', 'chu', 'cyu'],
  ちょ: ['tyo', 'cho', 'cyo'],
  ちぇ: ['tye', 'che', 'cye'],
  にゃ: ['nya'],
  にゅ: ['nyu'],
  にょ: ['nyo'],
  ひゃ: ['hya'],
  ひゅ: ['hyu'],
  ひょ: ['hyo'],
  みゃ: ['mya'],
  みゅ: ['myu'],
  みょ: ['myo'],
  りゃ: ['rya'],
  りゅ: ['ryu'],
  りょ: ['ryo'],
  ぎゃ: ['gya'],
  ぎゅ: ['gyu'],
  ぎょ: ['gyo'],
  じゃ: ['zya', 'ja', 'jya'],
  じゅ: ['zyu', 'ju', 'jyu'],
  じょ: ['zyo', 'jo', 'jyo'],
  じぇ: ['zye', 'je', 'jye'],
  ぢゃ: ['dya'],
  ぢゅ: ['dyu'],
  ぢょ: ['dyo'],
  びゃ: ['bya'],
  びゅ: ['byu'],
  びょ: ['byo'],
  ぴゃ: ['pya'],
  ぴゅ: ['pyu'],
  ぴょ: ['pyo'],
  ふぁ: ['fa'],
  ふぃ: ['fi'],
  ふぇ: ['fe'],
  ふぉ: ['fo'],
  ふゅ: ['fyu'],
  うぃ: ['wi', 'whi'],
  うぇ: ['we', 'whe'],
  うぉ: ['who'],
  てぃ: ['thi'],
  でぃ: ['dhi'],
  でゅ: ['dhu'],
  ゔぁ: ['va'],
  ゔぃ: ['vi'],
  ゔぇ: ['ve'],
  ゔぉ: ['vo'],
};

/** 「っ」を単独で打つ表記 */
export const SOKUON_STANDALONE: readonly string[] = ['xtu', 'ltu', 'xtsu', 'ltsu'];

/** 「っ」の子音重ねに使える先頭子音 */
export const DOUBLABLE = new Set('kstcfhmyrwgzjdbpvq');

/**
 * この文字が「ん」の直後に来るとき、「ん」を単独の n で打てない。
 * (母音・な行・や行・ん・小書き文字の前では n の解釈が曖昧になるため)
 */
export const N_BLOCKERS = new Set('あいうえおなにぬねのやゆよんゃゅょぁぃぅぇぉ');

/** 「ん」の表記。単独 n の可否は文脈で決まる */
export const N_SPELLINGS_FULL: readonly string[] = ['n', 'nn', 'xn'];
export const N_SPELLINGS_RESTRICTED: readonly string[] = ['nn', 'xn'];
